spring:
  profiles:
    active: dev

---
server:
  port: 7001

spring:
  profiles: dev
  application:
    name: microservicecloud-config-eureka

eureka:
  instance:
    hostname: eureka7001.com #eurekai服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #是否需要检索服务（检索服务是client端的事）
    service-url:
      #单个配置
      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #eureka注册中心访问地址
      #集群配置
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7002

spring:
  profiles: test
  application:
    name: microservicecloud-config-eureka

eureka:
  instance:
    hostname: eureka7002.com #eurekai服务端的实例名称
  client:
    register-with-eureka: false #false表示不向注册中心注册自己
    fetch-registry: false #是否需要检索服务（检索服务是client端的事）
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/